apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-${{ values.appName }}
spec:  
  template:         
    metadata:
      name: dsp-clone-job-${{ values.appName }}
    spec:  
      serviceAccountName: ${{ values.name }}-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=${{ values.name }}-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/${{ values.name }}-notebook -- git clone ${{ values.srcRepoURL }}
      restartPolicy: Never