apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  ${{ values.name }}
    app.kubernetes.io/part-of: ${{ values.name }}  
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  ${{ values.name }} 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  ${{ values.name }}
    spec:
      initContainers:
      - name: model-file
        image: ${{ values.initContainer }}
        command: ['/usr/bin/install', "/model/model.file", "/shared/"]
        volumeMounts:
        - name: model-file
          mountPath: /shared
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://0.0.0.0:${{ values.modelServicePort }}
        image:  ${{ values.appContainer }}
        name: app-inference
        ports:
        - containerPort: ${{ values.appPort }}
        securityContext:
          runAsNonRoot: true
      - env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "${{ values.modelServicePort }}"
        - name: MODEL_PATH
          value: /model/model.file
        image: ${{ values.modelServiceContainer }}
        name: app-model-service
        ports:
        - containerPort: ${{ values.modelServicePort }}
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: model-file
          mountPath: /model
      volumes:
      - name: model-file
        emptyDir: {}
