---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models-cache-${{ values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi